# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Thomsen
tagline:          'Image In the Mind'
description:      ''
url:              http://thomsen.github.com
baseurl:          '/'
safe:             false
paginate:         5

author:
  name:           'Thomsen'
  url:            https://

# Custom vars
version:          0.6.0
homedesc:         首页
srcdesc:          项目源码
versiondesc:      当前版本：
moredesc:         继续阅读

github:
  repo:           https://www.github.com/Thomsen/thomsen.github.com
