# Dependencies
#markdown:         redcarpet # redcarpet, rdiscount, kramdown, maruku
#highlighter:      pygments  # jekyll higher support
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Thomsen
tagline:          'Image In the Mind'
description:      ''
url:              http://thomsen.github.com
baseurl:          '/'
safe:             false
paginate:         5

# sass
sass:
  sass_dir:       _scss
  #style:          :compressed

author:
  name:           'Thomsen'
  url:            https://

# Custom vars
version:          0.8.6
homedesc:         首页
srcdesc:          项目源码
versiondesc:      当前版本：
moredesc:         继续阅读

image:
  path:           /public/images

github:
  repo:           https://www.github.com/Thomsen/thomsen.github.com

JB:
  version :       0.3.2

  archive_path:    /public/pages/archives/index.html
  categories_path: /public/pages/categories/index.html
  tags_path:       /public/pages/tags/index.html
  #atom_path:       /public/pages/atom.xml
  #rss_path:        /public/pages/rss.xml

  categories_list:
    provider:      custom

  pages_list:
    provider:      custom

  analytics:
    provider:      baidu
    baidu:
      tracking_id: "f4a58670867fe653f3ed0ce4e6c952dd"


  comemnts:

# Gems
gems: [jekyll-paginate]
