# Dependencies
markdown:         redcarpet  # redcarpet, rdiscount, kramdown, maruku
highlighter:      true  # pygments rename to highlighter

# Permalinks
permalink:        pretty

# Setup
title:            Thomsen
tagline:          'Image In the Mind'
description:      ''
url:              http://thomsen.github.com
baseurl:          '/'
safe:             true
paginate:         5

author:
  name:           'Thomsen'
  url:            https://

# Custom vars
version:          0.7.6
homedesc:         首页
srcdesc:          项目源码
versiondesc:      当前版本：
moredesc:         继续阅读

image:
  path:           /public/images

github:
  repo:           https://www.github.com/Thomsen/thomsen.github.com

JB:
  version :       0.3.2

  archive_path:    /public/pages/archives.html
  categories_path: /public/pages/categories.html
  tags_path:       /public/pages/tags.html
  atom_path:       /public/pages/atom.xml
  rss_path:        /public/pages/rss.xml

  analytics:
    provider:      baidu
    baidu:
      tracking_id: "f4a58670867fe653f3ed0ce4e6c952dd"
    
  
  comemnts:
    
