# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Thomsen
tagline:          'Image In the Mind'
description:      ''
url:              http://thomsen.github.com
baseurl:          '/'
paginate:         5

pages:
  page:
    title: 'Archive'
    url: '/archive'

author:
  name:           'Thomsen'
  url:            https://

# Custom vars
version:          0.5.0

github:
  repo:           https://www.github.com/Thomsen/thomsen.github.com
