# Dependencies
markdown:         redcarpet # redcarpet, rdiscount, kramdown, maruku
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Thomsen
tagline:          'Image In the Mind'
description:      ''
url:              http://thomsen.github.com
baseurl:          '/'
safe:             true
paginate:         5

author:
  name:           'Thomsen'
  url:            https://

# Custom vars
version:          0.7.0
homedesc:         首页
srcdesc:          项目源码
versiondesc:      当前版本：
moredesc:         继续阅读

image:
  path:           /public/images

github:
  repo:           https://www.github.com/Thomsen/thomsen.github.com

JB:
  version :       0.3.1

  archive_path:    /archives.html
  categories_path: /categories.html
  tags_path:       /tags.html
  atom_path:       /atom.xml
  rss_path:        /rss.xml

  analytics:
    provider:      baidu
    baidu:
      tracking_id: "f4a58670867fe653f3ed0ce4e6c952dd"
    
  
  comemnts:
    
